### ISSUE TITLE
RSpec 3 compatibility

### ISSUE THREAD

**Issue by mikowitz** [ferrous26/rspec-pride#8]
I whipped this up on a branch on my fork of the project so I could use it in another project: https://github.com/mikowitz/rspec-pride/tree/rspec3/

Not sure what your own thinking was in terms of adding support for RSpec 3, but feel free to merge/pull/steal any code on that branch if you want.

**Comment by ferrous26** [comment]
Done and released in v3.1.0

**Comment by liveh2o** [comment]
Yea! Thanks. :tada: :clap:
